### ISSUE TITLE
Audio and Video Encoding

### ISSUE THREAD

**Issue by Dzoge** [thespooler/ffmpeg-shard#2]
Hi,
currently comitted version does not implement video and audio encoding. Is it planned to release it?
Is there an estimated date?

Thank you.

**Comment by thespooler** [comment]
As of now, I don't plan on adding such a feature. I only needed the container/codecs information and I'm becoming increasingly wary of the way memory is allocated. I wouldn't recommend using this project without inspecting more closely the effect of the way ffmpeg allocates memory in a managed application. As an example, I have seen CAPI complain about SafeHandles being manipulated in an unsafe way, and since I'm not directly using CAPI, only .NET framework crypto streams, this smells like some sort of memory corruption. I haven't investigated much, since for my needs, it still seems to work ok.
